//! Countries and languages by what people call them: "Swedish" is `language:sv` or `country:SE` depending on the
//! kind, "Sweden" and "SE" are `country:SE`, and a country's Wikidata item is what a person's citizenship names.
//! The tables are Wikidata's (`names_table.rs`, generated by `scripts/names-table.py`).

use crate::names_table::{COUNTRIES, COUNTRY_ALIASES, LANGUAGES, LANGUAGE_ALIASES};
use crate::sel::name_key;

/// A known ISO 3166-1 code as the table spells it.
fn country_code(code: &str) -> Option<&'static str> {
    COUNTRIES.iter().find(|(c, _, _)| c.eq_ignore_ascii_case(code)).map(|(c, _, _)| *c)
}

fn language_code(code: &str) -> Option<&'static str> {
    LANGUAGES.iter().find(|(c, _)| c.eq_ignore_ascii_case(code)).map(|(c, _)| *c)
}

/// The country `given` names — a code, a name or a demonym — as its ISO 3166-1 code.
pub fn country(given: &str) -> Option<&'static str> {
    let given = given.trim();
    if given.len() == 2 {
        return country_code(given);
    }
    let key = name_key(given);
    COUNTRY_ALIASES.iter().find(|(alias, _)| *alias == key).map(|(_, code)| *code)
}

/// The language `given` names — a code or a name — as its ISO 639-1 code.
pub fn language(given: &str) -> Option<&'static str> {
    let given = given.trim();
    if given.len() == 2 {
        return language_code(given);
    }
    let key = name_key(given);
    LANGUAGE_ALIASES.iter().find(|(alias, _)| *alias == key).map(|(_, code)| *code)
}

pub fn country_name(code: &str) -> Option<&'static str> {
    COUNTRIES.iter().find(|(c, _, _)| *c == code).map(|(_, name, _)| *name)
}

pub fn language_name(code: &str) -> Option<&'static str> {
    LANGUAGES.iter().find(|(c, _)| *c == code).map(|(_, name)| *name)
}

/// The Wikidata item a citizen of `code`'s country is recorded under.
pub fn country_item(code: &str) -> Option<&'static str> {
    COUNTRIES.iter().find(|(c, _, _)| *c == code).map(|(_, _, item)| *item)
}

/// Whether a name or alias matches `q` as atlas's typeahead does: the whole name, or one of its words, starts with
/// it (both folded).
fn starts(name: &str, q: &str) -> bool {
    name.starts_with(q) || name.split(' ').any(|w| w.starts_with(q))
}

/// The countries a partial name matches, each once, in table order.
pub fn countries_matching(q: &str) -> Vec<&'static str> {
    matching(q, COUNTRY_ALIASES, COUNTRIES.iter().map(|(c, n, _)| (*c, *n)))
}

/// The languages a partial name matches.
pub fn languages_matching(q: &str) -> Vec<&'static str> {
    matching(q, LANGUAGE_ALIASES, LANGUAGES.iter().copied())
}

fn matching(
    q: &str,
    aliases: &'static [(&'static str, &'static str)],
    names: impl Iterator<Item = (&'static str, &'static str)>,
) -> Vec<&'static str> {
    let q = name_key(q);
    if q.is_empty() {
        return Vec::new();
    }
    let mut out: Vec<&'static str> = Vec::new();
    let named = names.filter(|(code, name)| code.eq_ignore_ascii_case(&q) || starts(&name_key(name), &q));
    let aliased = aliases.iter().filter(|(alias, _)| starts(alias, &q)).map(|&(_, code)| (code, ""));
    for (code, _) in named.chain(aliased) {
        if !out.contains(&code) {
            out.push(code);
        }
    }
    out
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn a_name_a_demonym_or_a_code_is_its_code() {
        assert_eq!(country("Sweden"), Some("SE"));
        assert_eq!(country("swedish"), Some("SE"));
        assert_eq!(country("se"), Some("SE"));
        assert_eq!(country("South Korean"), Some("KR"));
        assert_eq!(country("united states"), Some("US"));
        assert_eq!(country("English"), Some("GB"), "the kind says it is a country");
        assert_eq!(country("Narnia"), None);
        assert_eq!(language("Swedish"), Some("sv"));
        assert_eq!(language("SV"), Some("sv"));
        assert_eq!(language("Farsi"), Some("fa"));
        assert_eq!(language("Mandarin"), Some("zh"));
        assert_eq!(language("Klingon"), None);
    }

    #[test]
    fn a_citizenship_is_the_item_atlass_people_carry() {
        assert_eq!(country_item("SE"), Some("Q34"));
        assert_eq!(country_item("US"), Some("Q30"));
        // Danish and Dutch people are citizens of the kingdoms in Wikidata, which is what atlas matches.
        assert_eq!(country_item("DK"), Some("Q756617"));
        assert_eq!(country_item("NL"), Some("Q29999"));
        assert_eq!(country_item("DD"), Some("Q16957"), "a state that no longer exists");
        assert_eq!(country_name("DK"), Some("Denmark"));
    }

    #[test]
    fn a_partial_name_finds_its_countries_and_languages() {
        assert_eq!(countries_matching("swe"), ["SE"]);
        assert!(countries_matching("korea").contains(&"KR") && countries_matching("korea").contains(&"KP"));
        assert_eq!(languages_matching("swedish"), ["sv"]);
        assert!(languages_matching("x").is_empty() || languages_matching("x").iter().all(|c| c.len() == 2));
    }

    /// Every code an alias names is in the table, so a lookup never names a country it cannot describe.
    #[test]
    fn every_alias_names_a_code_in_the_table() {
        for (alias, code) in COUNTRY_ALIASES {
            assert!(country_code(code).is_some(), "{alias} → {code}");
        }
        for (alias, code) in LANGUAGE_ALIASES {
            assert!(language_code(code).is_some(), "{alias} → {code}");
        }
    }
}
